/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bane.alati.swinggui.normativi;

import java.sql.Connection;
import java.util.ArrayList;
import rs.bane.alati.swinggui.meni.MeniWindow;
import rs.bane.alati.swinggui.meni.Prozori;
import rs.bane.alati.model.normativi.Normativ;

/**
 *
 * @author Milan
 */
public class NormativiWindow extends javax.swing.JFrame {

    Connection ucinakConnection;

    /**
     * Creates new form GlavniProzor
     */
    public NormativiWindow() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public NormativiWindow(Connection ucinakConnection) {
        initComponents();
        this.ucinakConnection = ucinakConnection;
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        unosTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        izlazTextArea = new javax.swing.JTextArea();
        izracunajButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        unosMI = new javax.swing.JMenuItem();
        pregledMI = new javax.swing.JMenuItem();
        pracenjeMI = new javax.swing.JMenuItem();
        normativiMI = new javax.swing.JMenuItem();
        tehnologijeMI = new javax.swing.JMenuItem();
        popisMI = new javax.swing.JMenuItem();
        sistemiMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Normativi");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        unosTextArea.setColumns(20);
        unosTextArea.setRows(5);
        jScrollPane1.setViewportView(unosTextArea);

        izlazTextArea.setColumns(20);
        izlazTextArea.setRows(5);
        jScrollPane2.setViewportView(izlazTextArea);

        izracunajButton.setText("KALKULISI");
        izracunajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izracunajButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        unosMI.setText("Unos ucinaka");
        unosMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosMIActionPerformed(evt);
            }
        });
        jMenu1.add(unosMI);

        pregledMI.setText("Pregled ucinaka");
        pregledMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledMIActionPerformed(evt);
            }
        });
        jMenu1.add(pregledMI);

        pracenjeMI.setText("Pracenje proizvodnje");
        pracenjeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracenjeMIActionPerformed(evt);
            }
        });
        jMenu1.add(pracenjeMI);

        normativiMI.setText("Normativi za izvoz");
        normativiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normativiMIActionPerformed(evt);
            }
        });
        jMenu1.add(normativiMI);

        tehnologijeMI.setText("Tehnologije");
        tehnologijeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehnologijeMIActionPerformed(evt);
            }
        });
        jMenu1.add(tehnologijeMI);

        popisMI.setText("Popis");
        popisMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisMIActionPerformed(evt);
            }
        });
        jMenu1.add(popisMI);

        sistemiMI.setText("Sistemi");
        sistemiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemiMIActionPerformed(evt);
            }
        });
        jMenu1.add(sistemiMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(izracunajButton)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(izracunajButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izracunajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izracunajButtonActionPerformed
        ArrayList<String> listaNovih = new ArrayList();
        for (String linija : unosTextArea.getText().split("\\n")) {
            listaNovih.add(linija);
        }
        izlazTextArea.setText("");
        for (Normativ n : Normativ.izracunajNormative(listaNovih, ucinakConnection)) {
            try {
                System.out.println(n);
                izlazTextArea.setText(izlazTextArea.getText() + n.toString() + "\n");
            } catch (NullPointerException e) {

            }
        }
    }//GEN-LAST:event_izracunajButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Prozori.normativi = null;
    }//GEN-LAST:event_formWindowClosing

    private void unosMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosMIActionPerformed
        Prozori.openUnos();
    }//GEN-LAST:event_unosMIActionPerformed

    private void pregledMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledMIActionPerformed
        Prozori.openPregled();
    }//GEN-LAST:event_pregledMIActionPerformed

    private void pracenjeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracenjeMIActionPerformed
        Prozori.openPracenje();
    }//GEN-LAST:event_pracenjeMIActionPerformed

    private void normativiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normativiMIActionPerformed
        Prozori.openNormativi();
    }//GEN-LAST:event_normativiMIActionPerformed

    private void tehnologijeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehnologijeMIActionPerformed
        Prozori.openTehnologije();
    }//GEN-LAST:event_tehnologijeMIActionPerformed

    private void popisMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisMIActionPerformed
        Prozori.openPopis();
    }//GEN-LAST:event_popisMIActionPerformed

    private void sistemiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemiMIActionPerformed
        Prozori.openSistemi();
    }//GEN-LAST:event_sistemiMIActionPerformed

    public static NormativiWindow createAndOpen(Connection ucinakConnection) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormativiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormativiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormativiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormativiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        NormativiWindow nWind = new NormativiWindow(ucinakConnection);
        nWind.setLocationRelativeTo(null);
        nWind.setVisible(true);
        return nWind;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea izlazTextArea;
    private javax.swing.JButton izracunajButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem normativiMI;
    private javax.swing.JMenuItem popisMI;
    private javax.swing.JMenuItem pracenjeMI;
    private javax.swing.JMenuItem pregledMI;
    private javax.swing.JMenuItem sistemiMI;
    private javax.swing.JMenuItem tehnologijeMI;
    private javax.swing.JMenuItem unosMI;
    private javax.swing.JTextArea unosTextArea;
    // End of variables declaration//GEN-END:variables
}
