



INSERT INTO `Worker` (`name`, `last_name`, `contract_type`)
VALUES
 ('Aleksandar', 'Sladojević', 1),
 ('Aleksandar', 'Stevanović', 1),
 ('Aleksandra', 'Ilić', 0),
 ('Alen', 'Voćkić', 1),
 ('Boško', 'Živanović', 1), 
 ('Branko', 'Parabucki', 0), 
 ('Daliborka', 'Ćalić', 1),
 ('Damir', 'Magdić', 0),
 ('Danica', 'Golub', 1),
 ('Danijel', 'Matošević', 1),
 ('Dejan', 'Kemer', 0),
 ('Dejan', 'Šušnjar', 0),
 ('Dimitrije', 'Stojšić', 0), 
 ('Dragan', 'Popović', 0),
 ('Dragan', 'Ralić', 1),
 ('Dragan', 'Ružojčić', 1),
 ('Dragomir', 'Davidov', 0),
 ('Dušan', 'Milojević', 1),
 ('Dušanka', 'Kusturin', 1),
 ('Duško', 'Beleslijin', 0),
 ('Eržebet', 'Kiš', 1), 
 ('Franja', 'Gak', 1), 
 ('Goran', 'Kostić', 1), 
 ('Goran', 'Čabdarić', 1),
 ('Gordana', 'Graora', 0),
 ('Isidora', 'Katanić', 0),
 ('Jelena', 'Milković', 0),
 ('Jelena', 'Radenković', 0), 
 ('Jelena', 'Švenda', 1), 
 ('Kosa', 'Subotić', 0),
 ('Zoran', 'Lazendić', 0),
 ('Ljiljana', 'Vujević', 1),
 ('Ljiljana', 'Šipraga', 1), 
 ('Maja', 'Sarić', 1),
 ('Marija', 'Hadnađ', 1), 
 ('Marijana', 'Grubor', 1),
 ('Milan', 'Bunjevčev', 0),
 ('Milan', 'Kovač', 1), 
 ('Milan', 'Sejović', 0), 
 ('Milan', 'Trkulja', 1),
 ('Mile', 'Perenčević', 1),
 ('Mile', 'Vadić', 0),
 ('Milivoje', 'Vračarić', 0), 
 ('Mirko', 'Magdić', 1),
 ('Nemanja', 'Ignjatović', 1),
 ('Nikola', 'Sekulić', 1),
 ('Petar', 'Kemiveš', 0),
 ('Petar', 'Minić', 0),
 ('Početno', 'stanje', 1),
 ('Predrag', 'Čanak', 1),
 ('Rade', 'Bošković', 1),
 ('Radojka', 'Vranešević', 1),
 ('Radomir', 'Bunjevčev', 0),
 ('Ratko', 'Šipraga', 1),
 ('Rudolf', 'Kovač', 1),
 ('Saša', 'Brajović', 0),
 ('Siniša', 'Gak', 1),
 ('Siniša', 'Subotić', 0),
 ('Slavomir', 'Josić', 1),
 ('Slađan', 'Kozarević', 1),
 ('Slobodan', 'Bačić', 1), 
 ('Slobodan', 'Savić', 0),
 ('Slobodan', 'Vojvodić', 0),
 ('Stana', 'Vulin', 0), 
 ('Stevan', 'Beljanski', 1),
 ('Stevan', 'Loboda', 0),
 ('Stevan', 'Žužić', 1),
 ('Stipan', 'Bešlin', 0), 
 ('Tanja', 'Narančić', 0),
 ('Valerija', 'Sabo', 1),
 ('Vinko', 'Pavičić', 1),
 ('Vladimir', 'Janković', 1),
 ('Zoran', 'Kožul', 0), 
 ('Šandor', 'Dorotić', 0),
 ('Žana', 'Malešević', 1),
 ('Željko', 'Kljajić', 1), 
 ('Đorđe', 'Popović', 0);


