/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bane.alati.swinggui.cilindri;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import rs.bane.alati.model.cilindri.Cilindar;
import rs.bane.alati.model.cilindri.Jedinica;
import rs.bane.alati.model.cilindri.JednaKombinacija;
import rs.bane.alati.model.cilindri.Kljuc;
import rs.bane.alati.swinggui.meni.Prozori;

/**
 *
 * @author bunjac
 */
public class SistemiWindow extends javax.swing.JFrame {

    /**
     * Creates new form SistemiWindow
     */
    public SistemiWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brojRezovaS = new javax.swing.JSpinner();
        maxRezS = new javax.swing.JSpinner();
        maxPrviRezS = new javax.swing.JSpinner();
        maxRazlikaRezovaS = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brJedinicaS = new javax.swing.JSpinner();
        brKljucevaS = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        generisanKljucTB = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        unosMI = new javax.swing.JMenuItem();
        pregledMI = new javax.swing.JMenuItem();
        pracenjeMI = new javax.swing.JMenuItem();
        normativiMI = new javax.swing.JMenuItem();
        tehnologijeMI = new javax.swing.JMenuItem();
        popisMI = new javax.swing.JMenuItem();
        sistemiMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        brojRezovaS.setModel(new javax.swing.SpinnerNumberModel(5, 0, 10, 1));

        maxRezS.setModel(new javax.swing.SpinnerNumberModel(9, 0, 15, 1));

        maxPrviRezS.setModel(new javax.swing.SpinnerNumberModel(6, 0, 15, 1));

        maxRazlikaRezovaS.setModel(new javax.swing.SpinnerNumberModel(6, 0, 15, 1));

        jLabel1.setText("Broj rezova");

        jLabel2.setText("Max rez");

        jLabel3.setText("Max prvi rez");

        jLabel4.setText("Max razlika susednih rezova");

        jButton1.setText("generisi kljuc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { "Jedinica 1",  'x'}
            },
            new String [] {
                "Jedinica", "Kljuc 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class
            };
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            //public Class getColumnClass(int columnIndex) {
                //    return types [columnIndex];
                //}
        });
        table.setCellSelectionEnabled(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel5.setText("Broj jedinica");

        jLabel6.setText("Broj kljuèeva");

        brJedinicaS.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        brJedinicaS.setValue(1);
        brJedinicaS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brJedinicaSStateChanged(evt);
            }
        });

        brKljucevaS.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        brKljucevaS.setValue(1);
        brKljucevaS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brKljucevaSStateChanged(evt);
            }
        });

        jButton3.setText("dad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        generisanKljucTB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        generisanKljucTB.setText("00000");

        jMenu1.setText("File");

        unosMI.setText("Unos ucinaka");
        unosMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosMIActionPerformed(evt);
            }
        });
        jMenu1.add(unosMI);

        pregledMI.setText("Pregled ucinaka");
        pregledMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledMIActionPerformed(evt);
            }
        });
        jMenu1.add(pregledMI);

        pracenjeMI.setText("Pracenje proizvodnje");
        pracenjeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracenjeMIActionPerformed(evt);
            }
        });
        jMenu1.add(pracenjeMI);

        normativiMI.setText("Normativi za izvoz");
        normativiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normativiMIActionPerformed(evt);
            }
        });
        jMenu1.add(normativiMI);

        tehnologijeMI.setText("Tehnologije");
        tehnologijeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehnologijeMIActionPerformed(evt);
            }
        });
        jMenu1.add(tehnologijeMI);

        popisMI.setText("Popis");
        popisMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisMIActionPerformed(evt);
            }
        });
        jMenu1.add(popisMI);

        sistemiMI.setText("Sistemi");
        sistemiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemiMIActionPerformed(evt);
            }
        });
        jMenu1.add(sistemiMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxPrviRezS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maxRazlikaRezovaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maxRezS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(brojRezovaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brKljucevaS, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(brJedinicaS))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addComponent(generisanKljucTB))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brojRezovaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(generisanKljucTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxRezS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxPrviRezS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxRazlikaRezovaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brJedinicaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brKljucevaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Prozori.sistemi = null;
    }//GEN-LAST:event_formWindowClosing

    private void unosMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosMIActionPerformed
        Prozori.openUnos();
    }//GEN-LAST:event_unosMIActionPerformed

    private void pregledMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledMIActionPerformed
        Prozori.openPregled();
    }//GEN-LAST:event_pregledMIActionPerformed

    private void pracenjeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracenjeMIActionPerformed
        Prozori.openPracenje();
    }//GEN-LAST:event_pracenjeMIActionPerformed

    private void normativiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normativiMIActionPerformed
        Prozori.openNormativi();
    }//GEN-LAST:event_normativiMIActionPerformed

    private void tehnologijeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehnologijeMIActionPerformed
        Prozori.openTehnologije();
    }//GEN-LAST:event_tehnologijeMIActionPerformed

    private void popisMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisMIActionPerformed
        Prozori.openPopis();
    }//GEN-LAST:event_popisMIActionPerformed

    private void sistemiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemiMIActionPerformed
        Prozori.openSistemi();
    }//GEN-LAST:event_sistemiMIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jedinica.podesavanja((int) maxRezS.getValue(), (int) maxPrviRezS.getValue(), (int) maxRazlikaRezovaS.getValue(), (int) brojRezovaS.getValue());
        generisanKljucTB.setText(Kljuc.generisiRndKljuc().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jedinica.podesavanja((int) maxRezS.getValue(), (int) maxPrviRezS.getValue(),
                (int) maxRazlikaRezovaS.getValue(), (int) brojRezovaS.getValue());
        int[] rezovi = new int[generisanKljucTB.getText().length()];
        for (int i = 0; i < rezovi.length; i++) {
            rezovi[i] = Character.getNumericValue(generisanKljucTB.getText().charAt(i));
        }
        Kljuc kljuc = new Kljuc(rezovi);
        System.out.println(kljuc);
        System.out.println();
//        for (Cilindar c : kljuc.cilindriKojeOtkljucava(kljuc)) {
//            System.out.println(c);
//        }
        System.out.println(kljuc.cilindriKojeOtkljucava(kljuc).size());
    }//GEN-LAST:event_jButton2ActionPerformed
    int brJedinica = 1;
    private void brJedinicaSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brJedinicaSStateChanged
        if ((int) brJedinicaS.getValue() > brJedinica) {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            int x = dtm.getColumnCount();
            Object[] arr = new Object[x];
            arr[0] = "Jedinica " + (dtm.getRowCount() + 1);
            for (int i = 1; i < x; i++) {
                arr[i] = "";
            }
            dtm.addRow(arr);
        }
        if ((int) brJedinicaS.getValue() < brJedinica) {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.removeRow(dtm.getRowCount() - 1);
        }
        brJedinica = (int) brJedinicaS.getValue();
    }//GEN-LAST:event_brJedinicaSStateChanged
    int brKljuceva = 1;
    private void brKljucevaSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brKljucevaSStateChanged
        if ((int) brKljucevaS.getValue() > brKljuceva) {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            int x = dtm.getRowCount();
            Object[] arr = new Object[x];
            for (int i = 0; i < x; i++) {
                arr[i] = "";
            }
            dtm.addColumn("Kljuc " + dtm.getColumnCount(), arr);
        }
        if ((int) brKljucevaS.getValue() < brKljuceva) {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            DefaultTableModel ndtm = new DefaultTableModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                Object[] arr = new Object[dtm.getColumnCount() - 1];
                for (int j = 0; j < dtm.getColumnCount() - 1; j++) {
                    arr[j] = dtm.getValueAt(i, j);
                }
                ndtm.addRow(arr);
            }
            table.setModel(ndtm);
        }
        brKljuceva = (int) brKljucevaS.getValue();
    }//GEN-LAST:event_brKljucevaSStateChanged
    Object[][] matrica;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        matrica = new Object[table.getRowCount()][table.getColumnCount()];
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            for (int j = 0; j < dtm.getColumnCount(); j++) {
                matrica[i][j] = dtm.getValueAt(i, j);
                System.out.print(dtm.getValueAt(i, j) + " ");
            }
            System.out.println();
        }
        System.out.println();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getButton() == 1) {
            if (evt.getClickCount() == 2 && !evt.isConsumed()) {
                int i = table.getSelectedRow();
                int j = table.getSelectedColumn();
                if (j > 0) {
                    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                    if (/*dtm.getValueAt(i, j) == null ||*/!dtm.getValueAt(i, j).toString().equalsIgnoreCase("x")) {
                        dtm.setValueAt("X", i, j);
                    } else {
                        dtm.setValueAt("", i, j);
                    }
                }
            }
        }
    }//GEN-LAST:event_tableMouseClicked
    
    public static SistemiWindow createAndOpen() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemiWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SistemiWindow sWind = new SistemiWindow();
        sWind.setLocationRelativeTo(null);
        sWind.setVisible(true);
        return sWind;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner brJedinicaS;
    private javax.swing.JSpinner brKljucevaS;
    private javax.swing.JSpinner brojRezovaS;
    private javax.swing.JTextField generisanKljucTB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner maxPrviRezS;
    private javax.swing.JSpinner maxRazlikaRezovaS;
    private javax.swing.JSpinner maxRezS;
    private javax.swing.JMenuItem normativiMI;
    private javax.swing.JMenuItem popisMI;
    private javax.swing.JMenuItem pracenjeMI;
    private javax.swing.JMenuItem pregledMI;
    private javax.swing.JMenuItem sistemiMI;
    private javax.swing.JTable table;
    private javax.swing.JMenuItem tehnologijeMI;
    private javax.swing.JMenuItem unosMI;
    // End of variables declaration//GEN-END:variables
}
