/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bane.alati.swinggui.meni;

import java.io.IOException;
import java.sql.Connection;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.bane.alati.dao.ConnectionManager;
import rs.bane.alati.updater.Update;

/**
 *
 * @author Milan
 */
public class MeniWindow extends javax.swing.JFrame {

    Connection connection;
    Connection ucinakConnection;

    /**
     * Creates new form MainWindow
     */
    public MeniWindow() {
        Prozori.meni = this;
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            ConnectionManager.openConnection();
            connection = ConnectionManager.getIssupConnection();//Connecting.openIssupConnection();
        } catch (Exception ex) {
            Logger.getLogger(MeniWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (connection != null) {
            try {
                ucinakConnection = ConnectionManager.getUcinciConnection();//Connecting.openUcinakConnection();
            } catch (Exception ex) {
                Logger.getLogger(MeniWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ucinakConnection == null) {
                JOptionPane.showMessageDialog(this, "Nije uspostavljena konekcija sa bazom Ucinaka. "
                        + "Pogledajte properties!");
                ConnectionManager.closeConnection(connection);
                System.exit(0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nije uspostavljena konekcija sa serverom. Pogledajte properties!");
            System.exit(0);
        }
        Prozori.connection = connection;
        Prozori.ucinakConnection = ucinakConnection;
        try {
            verL.setText("v" + Update.getThisVersion(this.getClass()));
            if (Update.imaLiUpdate(this.getClass())) {
                Process proc = Runtime.getRuntime().exec("java -jar lib/updater.jar");
                //JOptionPane.showMessageDialog(this, "exit");
                System.exit(0);
            }
        } catch (IOException ex) {
            Logger.getLogger(MeniWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (StringIndexOutOfBoundsException ex) {
            Logger.getLogger(MeniWindow.class.getName()).log(Level.SEVERE, null, ex);
            verL.setText("v");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unosUcinakaBT = new javax.swing.JButton();
        pregledUcinakaBT = new javax.swing.JButton();
        pracenjeBT = new javax.swing.JButton();
        popisBT = new javax.swing.JButton();
        normativiBT = new javax.swing.JButton();
        sistemiBT = new javax.swing.JButton();
        verL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alati");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        unosUcinakaBT.setText("Unos ucinaka");
        unosUcinakaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosUcinakaBTActionPerformed(evt);
            }
        });

        pregledUcinakaBT.setText("Pregled  ucinaka");
        pregledUcinakaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledUcinakaBTActionPerformed(evt);
            }
        });

        pracenjeBT.setText("Pracenje proizvodnje");
        pracenjeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracenjeBTActionPerformed(evt);
            }
        });

        popisBT.setText("Popis");
        popisBT.setMaximumSize(new java.awt.Dimension(133, 23));
        popisBT.setMinimumSize(new java.awt.Dimension(133, 23));
        popisBT.setPreferredSize(new java.awt.Dimension(133, 23));
        popisBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisBTActionPerformed(evt);
            }
        });

        normativiBT.setText("Normativi izvoz");
        normativiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normativiBTActionPerformed(evt);
            }
        });

        sistemiBT.setText("Sistemi");
        sistemiBT.setMaximumSize(new java.awt.Dimension(133, 23));
        sistemiBT.setMinimumSize(new java.awt.Dimension(133, 23));
        sistemiBT.setPreferredSize(new java.awt.Dimension(133, 23));
        sistemiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemiBTActionPerformed(evt);
            }
        });

        verL.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(popisBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sistemiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unosUcinakaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pregledUcinakaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pracenjeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(normativiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(verL)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unosUcinakaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregledUcinakaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pracenjeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normativiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popisBT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sistemiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(verL)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ConnectionManager.closeConnection(connection);
        ConnectionManager.closeConnection(ucinakConnection);
        System.out.println("debug exit");
    }//GEN-LAST:event_formWindowClosing

    private void zatvoriMeni() {
        this.dispose();
        Prozori.meni = null;
    }

    private void unosUcinakaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosUcinakaBTActionPerformed
        Prozori.openUnos();
        zatvoriMeni();
    }//GEN-LAST:event_unosUcinakaBTActionPerformed

    private void pregledUcinakaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledUcinakaBTActionPerformed
        Prozori.openPregled();
        zatvoriMeni();
    }//GEN-LAST:event_pregledUcinakaBTActionPerformed

    private void pracenjeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracenjeBTActionPerformed
        Prozori.openPracenje();
        zatvoriMeni();
    }//GEN-LAST:event_pracenjeBTActionPerformed

    private void popisBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisBTActionPerformed
        Prozori.openPopis();
        zatvoriMeni();
    }//GEN-LAST:event_popisBTActionPerformed

    private void normativiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normativiBTActionPerformed
        Prozori.openNormativi();
        zatvoriMeni();
    }//GEN-LAST:event_normativiBTActionPerformed

    private void sistemiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemiBTActionPerformed
//        Prozori.openSistemi();
//        zatvoriMeni();
    }//GEN-LAST:event_sistemiBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeniWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeniWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeniWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeniWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Default locale: " + Locale.getDefault());
                Locale locale1 = new Locale("sr", "RS");
                Locale.setDefault(locale1);
                System.out.println("New local is set to: " + Locale.getDefault());
                new MeniWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton normativiBT;
    private javax.swing.JButton popisBT;
    private javax.swing.JButton pracenjeBT;
    private javax.swing.JButton pregledUcinakaBT;
    private javax.swing.JButton sistemiBT;
    private javax.swing.JButton unosUcinakaBT;
    private javax.swing.JLabel verL;
    // End of variables declaration//GEN-END:variables
}
