/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bane.alati.swinggui.analiza.proizvodnja;

import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import rs.bane.alati.swinggui.meni.Prozori;
import rs.bane.alati.dao.ExportPregledPorudzbineXLS;
import rs.bane.alati.model.analiza.proizvodnja.Porudzbina;
import rs.bane.alati.model.analiza.norme.DnevniUcinakRadnik;
import rs.bane.alati.dao.analiza.norme.NormaSQL;
import rs.bane.alati.dao.ExportNormeXLSX;
import rs.bane.alati.model.sastavnice.Sastavnica;
import static rs.bane.alati.model.sastavnice.Sastavnica.ucitajSastavnicu;
import rs.bane.alati.model.sastavnice.TehnoloskaOperacija;

/**
 *
 * @author Milan
 */
public class AnalizaWindow extends javax.swing.JFrame {

    private Connection ucinakConnection;
    private Connection connection;

    /**
     * Creates new form AnalizaWindow
     */
    public AnalizaWindow() {
        initComponents();
    }

    private AnalizaWindow(Connection ucinakConnection, Connection connection) {
        initComponents();
        this.ucinakConnection = ucinakConnection;
        this.connection = connection;
        datum();
    }

    private void datum() {
        godSpin.setValue(Calendar.getInstance().get(Calendar.YEAR));
        mesecCB.setSelectedIndex(Calendar.getInstance().get(Calendar.MONTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        mesecCB = new javax.swing.JComboBox<>();
        godSpin = new javax.swing.JSpinner();
        blankoRB = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        unosMI = new javax.swing.JMenuItem();
        pregledMI = new javax.swing.JMenuItem();
        pracenjeMI = new javax.swing.JMenuItem();
        normativiMI = new javax.swing.JMenuItem();
        tehnologijeMI = new javax.swing.JMenuItem();
        popisMI = new javax.swing.JMenuItem();
        sistemiMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pracenje proizvodnje");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("UCITAJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mesecCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar" }));

        godSpin.setModel(new javax.swing.SpinnerNumberModel(2017, 2008, 2050, 1));

        buttonGroup1.add(blankoRB);
        blankoRB.setSelected(true);
        blankoRB.setText("blanko");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("popunjeno");

        jButton2.setText("UCITAJ KULM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("NORME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("NORME SAST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        unosMI.setText("Unos ucinaka");
        unosMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosMIActionPerformed(evt);
            }
        });
        jMenu1.add(unosMI);

        pregledMI.setText("Pregled ucinaka");
        pregledMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledMIActionPerformed(evt);
            }
        });
        jMenu1.add(pregledMI);

        pracenjeMI.setText("Pracenje proizvodnje");
        pracenjeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracenjeMIActionPerformed(evt);
            }
        });
        jMenu1.add(pracenjeMI);

        normativiMI.setText("Normativi za izvoz");
        normativiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normativiMIActionPerformed(evt);
            }
        });
        jMenu1.add(normativiMI);

        tehnologijeMI.setText("Tehnologije");
        tehnologijeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehnologijeMIActionPerformed(evt);
            }
        });
        jMenu1.add(tehnologijeMI);

        popisMI.setText("Popis");
        popisMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisMIActionPerformed(evt);
            }
        });
        jMenu1.add(popisMI);

        sistemiMI.setText("Sistemi");
        sistemiMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemiMIActionPerformed(evt);
            }
        });
        jMenu1.add(sistemiMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(blankoRB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mesecCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(godSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesecCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(godSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blankoRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String brporS = JOptionPane.showInputDialog(this, "Unesite broj porudzbine");
        int brpor;
        try {
            brpor = Integer.parseInt(brporS);
            Porudzbina por = Porudzbina.ucitajNalog(brpor, connection);
            //System.out.println(por);
            int mesec = mesecCB.getSelectedIndex() + 1;
            int godina = (int) godSpin.getValue();
            boolean blanko = blankoRB.isSelected();
            if (ExportPregledPorudzbineXLS.export(por, mesec, godina, brporS, blanko, ucinakConnection)) {
                JOptionPane.showMessageDialog(this, "Uspesno exportovan!");
            } else {
                JOptionPane.showMessageDialog(this, "NIJE exportovan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pogresan format, unesite ceo broj!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Prozori.pracenje = null;
    }//GEN-LAST:event_formWindowClosing

    private void unosMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosMIActionPerformed
        Prozori.openUnos();
    }//GEN-LAST:event_unosMIActionPerformed

    private void pregledMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledMIActionPerformed
        Prozori.openPregled();
    }//GEN-LAST:event_pregledMIActionPerformed

    private void pracenjeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracenjeMIActionPerformed
        Prozori.openPracenje();
    }//GEN-LAST:event_pracenjeMIActionPerformed

    private void normativiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normativiMIActionPerformed
        Prozori.openNormativi();
    }//GEN-LAST:event_normativiMIActionPerformed

    private void tehnologijeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehnologijeMIActionPerformed
        Prozori.openTehnologije();
    }//GEN-LAST:event_tehnologijeMIActionPerformed

    private void popisMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisMIActionPerformed
        Prozori.openPopis();
    }//GEN-LAST:event_popisMIActionPerformed

    private void sistemiMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemiMIActionPerformed
        Prozori.openSistemi();
    }//GEN-LAST:event_sistemiMIActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String brporS = JOptionPane.showInputDialog(this, "Unesite broj porudzbine");
        int brpor;
        try {
            brpor = Integer.parseInt(brporS);
            Porudzbina por = Porudzbina.ucitajNalog(brpor, connection);
            //System.out.println(por);
            int mesec = mesecCB.getSelectedIndex() + 1;
            int godina = (int) godSpin.getValue();
            boolean blanko = blankoRB.isSelected();
            if (ExportPregledPorudzbineXLS.exportKulm(por, mesec, godina, brporS, blanko, ucinakConnection)) {
                JOptionPane.showMessageDialog(this, "Uspesno exportovan!");
            } else {
                JOptionPane.showMessageDialog(this, "NIJE exportovan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pogresan format, unesite ceo broj!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String katBr = JOptionPane.showInputDialog(this, "Unesite kataloški broj artikla:");
        String oper = JOptionPane.showInputDialog(this, "Unesite naziv operacije:");
        ArrayList<DnevniUcinakRadnik> list = NormaSQL.getList2(katBr, oper, ucinakConnection);
        if (ExportNormeXLSX.export(list, katBr, oper, connection)) {
            JOptionPane.showMessageDialog(this, "Uspesno exportovan!");
        } else {
            JOptionPane.showMessageDialog(this, "NIJE exportovan!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String ident = JOptionPane.showInputDialog(this, "Unesite ident artikla:");
        Sastavnica sas = ucitajSastavnicu(ident, 450, connection);
        String folder = "norme/" + sas.getKatBroj();
        rekur(sas, folder);

        JOptionPane.showMessageDialog(this, "Završen export!");

    }//GEN-LAST:event_jButton4ActionPerformed

    private ArrayList<ArrayList<DnevniUcinakRadnik>> poOper(Sastavnica sas) {
        ArrayList<ArrayList<DnevniUcinakRadnik>> lista = new ArrayList<>();
        if (sas.getTehPostupak() != null && sas.getTehPostupak().getOperacije() != null) {
            for (TehnoloskaOperacija top : sas.getTehPostupak().getOperacije()) {
                ArrayList<DnevniUcinakRadnik> list = NormaSQL.getList2(sas.getKatBroj(), top.getNaziv(), ucinakConnection);
                lista.add(list);
            }
        }
        return lista;
    }

    private void rekur(Sastavnica sas, String folder) {
        if (sas.getK() != 'S') {
            ArrayList<ArrayList<DnevniUcinakRadnik>> list = poOper(sas);
            ExportNormeXLSX.export2(list, sas.getKatBroj(), folder);
        }
        if (sas.getDeca() != null && sas.getDeca().size() > 0) {
            for (Sastavnica sas2 : sas.getDeca()) {
                rekur(sas2, folder);
            }
        }
    }

    public static AnalizaWindow createAndOpen(Connection ucinakConnection, Connection connection) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        AnalizaWindow aWind = new AnalizaWindow(ucinakConnection, connection);
        aWind.setLocationRelativeTo(null);
        aWind.setVisible(true);
        return aWind;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blankoRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner godSpin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JComboBox<String> mesecCB;
    private javax.swing.JMenuItem normativiMI;
    private javax.swing.JMenuItem popisMI;
    private javax.swing.JMenuItem pracenjeMI;
    private javax.swing.JMenuItem pregledMI;
    private javax.swing.JMenuItem sistemiMI;
    private javax.swing.JMenuItem tehnologijeMI;
    private javax.swing.JMenuItem unosMI;
    // End of variables declaration//GEN-END:variables
}
